### ISSUE TITLE
Docker app not responding at http://localhost/etf-webapp/

### ISSUE THREAD

**Issue by robsgnao** [etf-validator/etf-webapp-docker#14]
On behalf of a user.

When attempting to deploy ETF via Docker, I get as a result for the URL" http://localhost/etf-webapp/ " an empty page with one line: "Directory: /etf-webapp/." Could you please assist me to complete this deploy succesfully? My colleugue has the same problem, however, a few weeks ago, it worked properly. Thank you in advance. Best regards.

**Comment by jonherrmann** [comment]
Please check if updating the docker image fixes the issue. The updating process is described here: https://github.com/interactive-instruments/etf-webapp-docker/blob/master/README.md#update-etf

**Comment by robsgnao** [comment]
Thanks, works for our local installation at JRC, seems not to be working for the user who reported the issue initially... we are waiting for additional information from him.

**Comment by jonherrmann** [comment]
I close this issue due to inactivity and because we can not clearly reproduce it. This issue could have been related to this [one](https://github.com/etf-validator/etf-webapp/issues/150).

Please feel free to reopen it, if the issue occurs again.
